sudo: required

language: node_js

services:
  - docker

node_js: lts/erbium

cache: yarn

before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose

script:
  - yarn test
  - yarn lint

after_success:
  - docker rmi $(docker images -q)
  - yarn coveralls
  - yarn build
  - docker login -u $HUB_USER -p $HUB_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - export DEBUG_TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "debug_latest"; else echo "debug_$TRAVIS_BRANCH" ; fi`
  - docker build --pull -t exoframe/server:$TAG .
  - if [ -z "$TRAVIS_TAG" ]; then echo "No tag, skipping"; else docker tag exoframe/server:$TAG exoframe/server:$TRAVIS_TAG; fi
  # build debug docker image
  - docker build --pull -f Dockerfile-debug -t exoframe/server:$DEBUG_TAG .
  # push all images to registry
  - docker push exoframe/server

env:
  global:
    - secure: MaXI0FCf4/HYQLiR/5Nhm7cGPVkAwzZTnargcHRLZwOWbGZ29zcEHOtO8r71LC9XHx8cHnxgpWMJkZOlgNY7Y84KNQfnnVNJpxZ66uzIQyMblndIlNJ7Y0CtLVBEQO7GAswDLx1XAobLxaCaQ7ZTr1CDLRaY2N7DJT76mAN20Q4Yet3PxBWwn6bBK/imptD3ZIRMi7OztnUVdc5Y7GicTWQOXju0K3sSOJDKBKvTJRtLER/qYWJnOKRrWVkAo3J6/hyW1wR+50i3zDnsbSOTvK0UgXx5z0ak7sLByCtPyCCgGU2vs0pauoJhEsN1lhtzKzrVmgqg5Ink0E0xoN9JqSyNe+RJUqHGd7Y2HSD/QyxJU5WjDvfcYNLIewXhgvWPxnKfrtf73BaQ4KKZPM3LgPkYnYVXB09znVqxN7fKrBk8Ogj5Nyl2PoaT7+/qIlupLt6/jJIwVLOf2wl3PhBYC7fdZ+D4PK4DcMvDZvJFpi3rFmL1iR2lj7r5T5SvFR5o7aSLVKXfkzD0uA36wh1JXyYyHZzkdYQxMU7dtS/8lG0oENDHGwrOUfZcKdvuffv6caM3Oo/B8CLgCTNY8JIm5zNzk6ykVwgen3xkHNA+hwQ6T6zjG7lNpxNq53hWwvREjHRdr9iAEzKFUddisvL44A7JJyM6sqvAFe6tqI6nHbw=
    - secure: UFbvYkcpk5tpnmepegcIaYlThaVTeHHbVwnMUc5YWaP9dVTPXLQhOuvJQeZtf6zKc2VnOWeAyhOZqGipN7bTsAeO+50BOUQpEh1vu6AHY2+LHu1KBnR11ZATuOeqJFnki9gVEr5L99ALGT6/0bSMv5XJuZuzVn5nPJVGnerk7XDXTlmWIq+OW9fUeXnW0cHfO9GvA9cDEC4dojS8ltIRPJQwCqzgCxkYivXlNtjeuBfY/C/T615xwRPRF9v1ENBetfKB/csfKpVvyJ3/JW8hkiV67t8e+9WzA/ZxxFt8qb4s2ECOIDYeLlV2210TTwncRzeNYyzHJwmPr8gVvAX73QFTIA6kI1ywxBxqhRhLhjIu8nnc18sizKoCaqU03New2vjKZKEfkUQK6RGz6IIJOK/fSvU7zaahosqEtGhAca5fovcz0HK5icoQ72mSgoMRY8WXwGJYTYTdQ2Lcxsy0k7KU/MsXS2traYH0qUZ8De5xD2RXMqjn1z35Gm/47/GZXFzn0gTqRbh1Kv17vTxtz6qvoCqZPN9uq0H29LxfOFgNabQEJhTMmZXhZgth4AaUYBxeKwbjwBaceCzFTwwLVqU4YsfkVGzj+AqpiVDZREIsJc6vkZbKymafSMj5jsXtfJfMLMPsMnBi8REgG8yewq2iBPkGO0ClEzCNcHvkEjQ=

deploy:
  - provider: npm
    skip_cleanup: true
    email: yamalight@gmail.com
    api_key:
      secure: jx1saIbfvgwhhRJiNv0zlSGoCncgsyZCHTJM4GBmD832JB3TG8NPJJM3YRorZh+Z8UdIbqshYMfrxLkD7YrerHdC69c3ruLPc9XjThIYKpNSIUB++VH6aeGWk33KLuTFo9F2w9ByXWlyYGGapM75zfrj6nfmbCV6nBJDz6ecUC1j06l1l+V9p+JCbbcd0W7PEIzYlWCtDa7Ix8sPYK0sU7tHbBdQJB9t1Bn9sPJ/g3Qyb1DBBSHkG4UhZyXNQYyF0+GVgSYsXwzkxVJqN7K6HtEYmzRL57sLlDtk5yK9Fd5xyV0OSo3diWw6VOoywqHtznVSX1LSLfiapdYq9tQyvxqPYBA7lTtBpqQ+7iTWb0Mpp2ozhlM00LGyKiWxX6OgrveBbQcJS4GTVDkdPzZB8DSh+MsGA2nSJD4hHu0WdsLdUNIhHXV937LDbuPozngbxpm6jj2BU+cnIuaeoKyLh29Kke1dIrj2pFy3Rnki/LdPoZ6sXLn4AqEi4Iish5rPdMfVZ+Emd+H59R0MBc/N6/lmWtiFowDyuOBNYDFJc1SF0Fgs1oIMZqVv7gUMkMKg9zSZFDbFo2nuQzu/W7uGujA9Ry6u2l3Tx2Gya4Anlm+ebIDeK042EeXNx1HU8SPmP4QEKPQfQyjauxIZ9t/Mk1NAAEYuIRwSIOr0Akxs0Ng=
    on:
      repo: exoframejs/exoframe-server
      tags: true
  - provider: npm
    skip_cleanup: true
    tag: next
    email: yamalight@gmail.com
    api_key:
      secure: jx1saIbfvgwhhRJiNv0zlSGoCncgsyZCHTJM4GBmD832JB3TG8NPJJM3YRorZh+Z8UdIbqshYMfrxLkD7YrerHdC69c3ruLPc9XjThIYKpNSIUB++VH6aeGWk33KLuTFo9F2w9ByXWlyYGGapM75zfrj6nfmbCV6nBJDz6ecUC1j06l1l+V9p+JCbbcd0W7PEIzYlWCtDa7Ix8sPYK0sU7tHbBdQJB9t1Bn9sPJ/g3Qyb1DBBSHkG4UhZyXNQYyF0+GVgSYsXwzkxVJqN7K6HtEYmzRL57sLlDtk5yK9Fd5xyV0OSo3diWw6VOoywqHtznVSX1LSLfiapdYq9tQyvxqPYBA7lTtBpqQ+7iTWb0Mpp2ozhlM00LGyKiWxX6OgrveBbQcJS4GTVDkdPzZB8DSh+MsGA2nSJD4hHu0WdsLdUNIhHXV937LDbuPozngbxpm6jj2BU+cnIuaeoKyLh29Kke1dIrj2pFy3Rnki/LdPoZ6sXLn4AqEi4Iish5rPdMfVZ+Emd+H59R0MBc/N6/lmWtiFowDyuOBNYDFJc1SF0Fgs1oIMZqVv7gUMkMKg9zSZFDbFo2nuQzu/W7uGujA9Ry6u2l3Tx2Gya4Anlm+ebIDeK042EeXNx1HU8SPmP4QEKPQfQyjauxIZ9t/Mk1NAAEYuIRwSIOr0Akxs0Ng=
    on:
      repo: exoframejs/exoframe-server
      branch: develop
